services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  cli:
    build:
      context: ./backend
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
